name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ vars.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t ${{ vars.DOCKER_USERNAME }}/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ${{ vars.DOCKER_USERNAME }}/react-test npm test

      - run: docker build -t ${{ vars.DOCKER_USERNAME }}/multi-client ./client
      - run: docker build -t ${{ vars.DOCKER_USERNAME }}/multi-nginx ./nginx
      - run: docker build -t ${{ vars.DOCKER_USERNAME }}/multi-server ./server
      - run: docker build -t ${{ vars.DOCKER_USERNAME }}/multi-worker ./worker

      - run: docker push ${{ vars.DOCKER_USERNAME }}/multi-client
      - run: docker push ${{ vars.DOCKER_USERNAME }}/multi-nginx
      - run: docker push ${{ vars.DOCKER_USERNAME }}/multi-server
      - run: docker push ${{ vars.DOCKER_USERNAME }}/multi-worker
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_key: "${{ secrets.AWS_SECRET_KEY }}"
          application_name: multi-docker
          environment_name: Multi-docker-env-1 
          existing_bucket_name: elasticbeanstalk-us-east-1-861276098873
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
